### ISSUE TITLE
convert bodypix js model to pb . then convert pb to tflite

### ISSUE THREAD

**Issue by HHMedic** [hegman12/body_pix_tflite#10]
Hello. I wanna convert bodypix js model to pb . then convert pb to tflite. 

the steps are https://github.com/patlevin/tfjs-to-tf/issues/32

I change some code as patlevin suggest. but produce the following error:

![image](https://user-images.githubusercontent.com/26923800/110914099-e2c33b80-8350-11eb-9ea0-681bb08f2c68.png)

I need do any other changes ?

**Comment by hegman12** [comment]
Hi,
It is difficult to help without simple reproducible test case. My guess here is your tflite model input for image is named as sub_2 whereas in the plugin, I named it as "image". So if you change line 211 in BodyPixPlugin.java, "image" to "sub_2" error could disappear. But even if you do that, you will get further errors as your tflite model only takes 1 input(sub_2) where as the BodyPixPlugin.java plugin passes 3 inputs to run model.

But if your goal is to use resnet50 instead of MobileNetV1, changes are rather very simple. After downloading weights of resnet50, as in the [converter](https://github.com/hegman12/body_pix_tflite/blob/master/converter_example/bodypix_MobileNetV1_to_tflite_converter.ipynb) example,there is a method `run_body_pix` inside class `MobileNetV1`. You just need to change this line

`normalizedTensor=tf.math.subtract(tf.math.divide(afterPadding["paddedTensor"],127.0),1.0)`

to resnet50 standard preprocessing. Rest should work fine and you should be able to use the plugin as is without much change.
Good luck.

**Comment by HHMedic** [comment]
Thanks. @hegman12 .

is MobileNetV1 is more suit for run on Android phone?
